class_name Track
extends Node3D
## A drivable track generated by sweeping a profile along a centreline curve.
##
## Each band becomes its own body carrying a `surface_friction` meta, which is
## how the car learns that it has put two wheels on the runoff without the
## physics needing to know anything about tracks.

const SURFACE_META: StringName = &"surface_friction"
const SURFACE_NAME_META: StringName = &"surface_name"

const ROAD_SHADER := """
shader_type spatial;
void fragment() {
	float edge = min(UV.x, 1.0 - UV.x);
	float line = smoothstep(0.014, 0.006, edge);
	ALBEDO = mix(vec3(0.085, 0.088, 0.095), vec3(0.86, 0.87, 0.88), line);
	ROUGHNESS = mix(0.82, 0.55, line);
}
"""

const KERB_SHADER := """
shader_type spatial;
void fragment() {
	float stripe = mod(floor(UV.y / 2.4), 2.0);
	ALBEDO = mix(vec3(0.78, 0.13, 0.13), vec3(0.88, 0.88, 0.90), stripe);
	ROUGHNESS = 0.7;
}
"""

var curve: Curve3D
var profile: TrackProfile = TrackProfile.new()
var closed: bool = true

var _frames: Array[Transform3D] = []


func build() -> void:
	for child: Node in get_children():
		child.queue_free()

	if curve == null or curve.point_count < 3:
		Log.error("Track", "Cannot build: curve has fewer than three points")
		return

	_frames = TrackGeometry.sample_frames(curve, profile.sample_spacing)
	for band: Dictionary in profile.bands():
		_build_band(band)

	Log.info("Track", "Built %.0f m from %d cross-sections" % [length(), _frames.size()])


func length() -> float:
	return 0.0 if curve == null else curve.get_baked_length()


## Where a car should start the lap, sitting on the road rather than in it.
func start_transform(ride_height: float) -> Transform3D:
	if _frames.is_empty():
		return Transform3D.IDENTITY
	var frame := _frames[0]
	return Transform3D(frame.basis, frame.origin + frame.basis.y * ride_height)


func frame_at_distance(distance: float) -> Transform3D:
	var total := length()
	if total <= 0.0:
		return Transform3D.IDENTITY
	return TrackGeometry.frame_at(curve, fposmod(distance, total), total)


func _build_band(band: Dictionary) -> void:
	var surface: TrackProfile.Surface = band["surface"]
	var built := TrackGeometry.build_band(_frames, band["inner"], band["outer"], closed)
	var mesh: ArrayMesh = built["mesh"]
	if mesh == null:
		return

	var body := StaticBody3D.new()
	body.name = "%s_%d" % [TrackProfile.SURFACE_NAMES[surface], get_child_count()]
	body.set_meta(SURFACE_META, float(TrackProfile.FRICTION[surface]))
	body.set_meta(SURFACE_NAME_META, TrackProfile.SURFACE_NAMES[surface])

	var visual := MeshInstance3D.new()
	visual.mesh = mesh
	visual.material_override = _material(surface)
	body.add_child(visual)

	var collision_shape := ConcavePolygonShape3D.new()
	collision_shape.set_faces(built["faces"])
	# Winding across a swept surface is easy to get inconsistent, and a
	# one-sided barrier the car drives straight through is worse than the cost
	# of testing both faces.
	collision_shape.backface_collision = true

	var collider := CollisionShape3D.new()
	collider.shape = collision_shape
	body.add_child(collider)

	add_child(body)


func _material(surface: TrackProfile.Surface) -> Material:
	match surface:
		TrackProfile.Surface.ROAD:
			return _shader_material(ROAD_SHADER)
		TrackProfile.Surface.KERB:
			return _shader_material(KERB_SHADER)
		TrackProfile.Surface.RUNOFF:
			return _plain(Color(0.30, 0.29, 0.24), 0.95)
		_:
			return _plain(Color(0.72, 0.73, 0.76), 0.6)


func _shader_material(code: String) -> ShaderMaterial:
	var shader := Shader.new()
	shader.code = code
	var material := ShaderMaterial.new()
	material.shader = shader
	return material


func _plain(colour: Color, roughness: float) -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.albedo_color = colour
	material.roughness = roughness
	material.cull_mode = BaseMaterial3D.CULL_DISABLED
	return material
